# Generated by Django 3.1.2 on 2023-05-18 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_carrito'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='carrito',
            table='db_carrito',
        ),
    ]
