# Generated by Django 3.1.2 on 2023-06-21 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_producto_descuento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='descuento',
        ),
    ]
