# Generated by Django 3.1.2 on 2023-05-21 01:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20230518_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='vencimiento',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
