# Generated by Django 3.1.2 on 2023-05-21 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20230520_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='cantidad_agregada',
            field=models.IntegerField(default=0),
        ),
    ]
