# Generated by Django 3.1.2 on 2023-06-22 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_carrito_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='usuario',
        ),
    ]
